# Generated by Django 2.0.6 on 2018-09-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
