# Generated by Django 2.0.6 on 2018-09-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_auto_20180921_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
