# Generated by Django 2.0.6 on 2018-09-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_investor_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hour',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=20, help_text='The hourly rate paid for work.', max_digits=8),
            preserve_default=False,
        ),
    ]
