# Generated by Django 2.1.3 on 2018-12-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_hour_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='hours',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
