# Generated by Django 2.1.3 on 2018-12-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_auto_20181201_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
