# Generated by Django 2.1.3 on 2018-12-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_auto_20181201_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetvalue',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
