# Generated by Django 2.1.3 on 2019-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_auto_20181202_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalDividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assetvalue',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
