# Generated by Django 2.1.3 on 2019-06-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_auto_20190602_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TotalDividend',
            new_name='Dividend',
        ),
    ]
