# Generated by Django 2.1.3 on 2019-06-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_auto_20190602_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividend',
            options={'verbose_name': 'Monthly Dividend Payout', 'verbose_name_plural': 'Monthly Dividend Payout'},
        ),
    ]
