# Generated by Django 2.1.3 on 2020-04-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0017_transaction_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='property',
            new_name='asset',
        ),
    ]
